#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_shadow                off
yabai -m config window_opacity               on
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap
# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  4 
yabai -m config bottom_padding               4 
yabai -m config left_padding                 4 
yabai -m config right_padding                4 
yabai -m config window_gap                   4 
yabai -m rule --add app=System\ Preferences manage=off
yabai -m rule --add app=Digital\ Color\ Meter manage=off
yabai -m rule --add app=mpv manage=off

echo "yabai configuration loaded.."
